spring:
  application:
    name: vn-be
  datasource:
    url: jdbc:postgresql://localhost:5433/vndb
    username: vndb
    password: vndb
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  docker:
    compose:
      enabled: false
  flyway:
    enabled: false
